Increase blocksize of dd imaging to 4 MiB for nearly 3x speedup

diff --git a/hybris-installer/META-INF/com/google/android/update-binary b/hybris-installer/META-INF/com/google/android/update-binary
--- a/hybris-installer/META-INF/com/google/android/update-binary
+++ b/hybris-installer/META-INF/com/google/android/update-binary
@@ -148,7 +148,7 @@ log "Disabling forced encryption in vendor fstab..."
  (umount /vendor &> /dev/null; mount -o rw /vendor && sed "s/fileencryption/encryptable/" -i /vendor/etc/fstab.qcom && sed "s/forceencrypt/encryptable/" -i /vendor/etc/fstab.qcom) || log "Couldn't disable forced encryption!"
 umount /vendor &
 
-if [[ "$TARGET_LOS_VER" = "16.0" && ! -f $ROOT/lib/systemd/system/mnt-vendor-persist.mount ]]; then
+if [[ "$TARGET_LOS_VER" = "17.1" && ! -f $ROOT/lib/systemd/system/mnt-vendor-persist.mount ]]; then
 	log "Mount unit for persist not found; copying current /persist to rootfs..."
 	mkdir -p $ROOT/mnt/vendor/persist /persist
 	if mount $PARTITION_PERSIST /persist; then
@@ -161,14 +161,14 @@ fi
 
 if [ "$FORCE_REINSTALL" = "0" ]; then
 	log "Backing up droid-boot image..."
-	dd if=$PARTITION_BOOT of=$ROOT/boot/droid-boot.img bs=4m
+	dd if=/dev/block/bootdevice/by-name/boot of=$ROOT/boot/droid-boot.img bs=4m
 elif [ -f /tmp/droid-boot.img ]; then
 	log "Moving back droid-boot image..."
 	mv /tmp/droid-boot.img $ROOT/boot/
 fi
 
 log "Writing hybris-boot image..."
-dd if=$ROOT/boot/hybris-boot.img of=$PARTITION_BOOT bs=4m || abort 11 "Couldn't write Hybris boot image!"
+dd if=$ROOT/boot/hybris-boot.img of=/dev/block/bootdevice/by-name/boot bs=4m || abort 11 "Couldn't write Hybris boot image!"
 
 log "Symlinking boot images to /sdcard..."
 ln -s $ROOT/boot/droid-boot.img /sdcard/
